// Generated by delombok at Mon Sep 03 20:16:23 CEST 2018
package io.spring.lombok;

import com.sun.istack.internal.NotNull;
import java.io.InputStream;
/*
Check exceptions burden
*/
public class LombokExample7 {
    @NotNull
    private String ejemplo1;
    @NotNull
    private String ejemplo2;
    @NotNull
    private String ejemplo3;
    @NotNull
    private String ejemplo4;
    @NotNull
    private String ejemplo5;
    @NotNull
    private Double id;

    public void main() {
        try {
            try (InputStream ex = this.getClass().getResourceAsStream("ejample.txt")) {
                id = null;
            }
        } catch (final java.lang.Throwable $ex) {
            throw lombok.Lombok.sneakyThrow($ex);
        }
    }

    public void main2() {
        InputStream ex = this.getClass().getResourceAsStream("ejample.txt");
        try {
        } finally {
            if (java.util.Collections.singletonList(ex).get(0) != null) {
                ex.close();
            }
        }
    }

    @java.lang.SuppressWarnings("all")
    public LombokExample7() {
    }
}
