// Generated by delombok at Mon Sep 03 20:16:23 CEST 2018
package io.spring.lombok;
/*
Builder pattern
*/
public class LombokExample5 {
    private String ejemplo1;
    private String ejemplo2;
    private String ejemplo3;
    private String ejemplo4;
    private String ejemplo5;
    private Double id;

    @java.lang.SuppressWarnings("all")
    LombokExample5(final String ejemplo1, final String ejemplo2, final String ejemplo3, final String ejemplo4, final String ejemplo5, final Double id) {
        this.ejemplo1 = ejemplo1;
        this.ejemplo2 = ejemplo2;
        this.ejemplo3 = ejemplo3;
        this.ejemplo4 = ejemplo4;
        this.ejemplo5 = ejemplo5;
        this.id = id;
    }


    @java.lang.SuppressWarnings("all")
    public static class LombokExample5Builder {
        @java.lang.SuppressWarnings("all")
        private String ejemplo1;
        @java.lang.SuppressWarnings("all")
        private String ejemplo2;
        @java.lang.SuppressWarnings("all")
        private String ejemplo3;
        @java.lang.SuppressWarnings("all")
        private String ejemplo4;
        @java.lang.SuppressWarnings("all")
        private String ejemplo5;
        @java.lang.SuppressWarnings("all")
        private Double id;

        @java.lang.SuppressWarnings("all")
        LombokExample5Builder() {
        }

        @java.lang.SuppressWarnings("all")
        public LombokExample5Builder ejemplo1(final String ejemplo1) {
            this.ejemplo1 = ejemplo1;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public LombokExample5Builder ejemplo2(final String ejemplo2) {
            this.ejemplo2 = ejemplo2;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public LombokExample5Builder ejemplo3(final String ejemplo3) {
            this.ejemplo3 = ejemplo3;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public LombokExample5Builder ejemplo4(final String ejemplo4) {
            this.ejemplo4 = ejemplo4;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public LombokExample5Builder ejemplo5(final String ejemplo5) {
            this.ejemplo5 = ejemplo5;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public LombokExample5Builder id(final Double id) {
            this.id = id;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public LombokExample5 build() {
            return new LombokExample5(ejemplo1, ejemplo2, ejemplo3, ejemplo4, ejemplo5, id);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "LombokExample5.LombokExample5Builder(ejemplo1=" + this.ejemplo1 + ", ejemplo2=" + this.ejemplo2 + ", ejemplo3=" + this.ejemplo3 + ", ejemplo4=" + this.ejemplo4 + ", ejemplo5=" + this.ejemplo5 + ", id=" + this.id + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static LombokExample5Builder builder() {
        return new LombokExample5Builder();
    }
}
