// Generated by delombok at Mon Sep 03 20:16:23 CEST 2018
package io.spring.lombok;

import lombok.*;
/*
Generate getters and setters for whole class
*/
public class LombokExample1 {
    private String ejemplo1;
    private String ejemplo2;
    private String ejemplo3;
    private String ejemplo4;
    private String ejemplo5;
    private Double example1;

    @java.lang.SuppressWarnings("all")
    public LombokExample1() {
    }

    @java.lang.SuppressWarnings("all")
    public LombokExample1(final String ejemplo1, final String ejemplo2, final String ejemplo3, final String ejemplo4, final String ejemplo5, final Double example1) {
        this.ejemplo1 = ejemplo1;
        this.ejemplo2 = ejemplo2;
        this.ejemplo3 = ejemplo3;
        this.ejemplo4 = ejemplo4;
        this.ejemplo5 = ejemplo5;
        this.example1 = example1;
    }

    @java.lang.SuppressWarnings("all")
    public String getEjemplo1() {
        return this.ejemplo1;
    }

    @java.lang.SuppressWarnings("all")
    public String getEjemplo2() {
        return this.ejemplo2;
    }

    @java.lang.SuppressWarnings("all")
    public String getEjemplo3() {
        return this.ejemplo3;
    }

    @java.lang.SuppressWarnings("all")
    public String getEjemplo4() {
        return this.ejemplo4;
    }

    @java.lang.SuppressWarnings("all")
    public String getEjemplo5() {
        return this.ejemplo5;
    }

    @java.lang.SuppressWarnings("all")
    public Double getExample1() {
        return this.example1;
    }

    @java.lang.SuppressWarnings("all")
    public void setEjemplo1(final String ejemplo1) {
        this.ejemplo1 = ejemplo1;
    }

    @java.lang.SuppressWarnings("all")
    public void setEjemplo2(final String ejemplo2) {
        this.ejemplo2 = ejemplo2;
    }

    @java.lang.SuppressWarnings("all")
    public void setEjemplo3(final String ejemplo3) {
        this.ejemplo3 = ejemplo3;
    }

    @java.lang.SuppressWarnings("all")
    public void setEjemplo4(final String ejemplo4) {
        this.ejemplo4 = ejemplo4;
    }

    @java.lang.SuppressWarnings("all")
    public void setEjemplo5(final String ejemplo5) {
        this.ejemplo5 = ejemplo5;
    }

    @java.lang.SuppressWarnings("all")
    public void setExample1(final Double example1) {
        this.example1 = example1;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "LombokExample1(ejemplo1=" + this.getEjemplo1() + ", ejemplo2=" + this.getEjemplo2() + ", ejemplo3=" + this.getEjemplo3() + ", ejemplo4=" + this.getEjemplo4() + ", ejemplo5=" + this.getEjemplo5() + ", example1=" + this.getExample1() + ")";
    }
}
