// Generated by delombok at Mon Sep 03 20:16:23 CEST 2018
package io.spring.lombok;
/*
Generates a constructor for all final fields, with parameter order same as field order
Creates an empty constructor.
Creates a constructor for all fields
*/
public class LombokExample3 {
    private String ejemplo1;
    private String ejemplo2;
    private String ejemplo3;
    private String ejemplo4;
    private String ejemplo5;
    private Double example1;

    @java.lang.SuppressWarnings("all")
    public LombokExample3(final String ejemplo1, final String ejemplo2, final String ejemplo3, final String ejemplo4, final String ejemplo5, final Double example1) {
        this.ejemplo1 = ejemplo1;
        this.ejemplo2 = ejemplo2;
        this.ejemplo3 = ejemplo3;
        this.ejemplo4 = ejemplo4;
        this.ejemplo5 = ejemplo5;
        this.example1 = example1;
    }

    @java.lang.SuppressWarnings("all")
    public LombokExample3() {
    }
}
