// Generated by delombok at Mon Sep 03 20:16:23 CEST 2018
package io.spring.lombok;
/*
More detail getters and setters
When you don't want getters and setters for all fields
and also maybe control access modifiers
*/
public class LombokExample2 {
    private String ejemplo1;
    private String ejemplo2;
    private String ejemplo3;
    private String ejemplo4;
    private String ejemplo5;
    private Double example1;

    @java.lang.SuppressWarnings("all")
    protected String getEjemplo1() {
        return this.ejemplo1;
    }

    @java.lang.SuppressWarnings("all")
    protected void setEjemplo1(final String ejemplo1) {
        this.ejemplo1 = ejemplo1;
    }

    @java.lang.SuppressWarnings("all")
    String getEjemplo2() {
        return this.ejemplo2;
    }

    @java.lang.SuppressWarnings("all")
    void setEjemplo2(final String ejemplo2) {
        this.ejemplo2 = ejemplo2;
    }

    @java.lang.SuppressWarnings("all")
    public String getEjemplo3() {
        return this.ejemplo3;
    }

    @java.lang.SuppressWarnings("all")
    public void setEjemplo3(final String ejemplo3) {
        this.ejemplo3 = ejemplo3;
    }

    @java.lang.SuppressWarnings("all")
    protected Double getExample1() {
        return this.example1;
    }

    @java.lang.SuppressWarnings("all")
    protected void setExample1(final Double example1) {
        this.example1 = example1;
    }
}
