// Generated by delombok at Mon Sep 03 20:16:23 CEST 2018
package io.spring.lombok;
/*
Create a logs
*/
public class LombokExample6 {
    @java.lang.SuppressWarnings("all")
    private static final java.util.logging.Logger log = java.util.logging.Logger.getLogger(LombokExample6.class.getName());

    public static void main() {
        log.info("greado");
    }
}
